# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'
project 'AnyThinkSDKDemo.xcodeproj'

def share_pods
  
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MJRefresh'


end

target 'AnyThinkSDKDemo' do
  
  post_install do |installer|
        installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
        end
      end
  
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  share_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # 国内
  # pod 'AnyThinkiOS','6.3.62'
  # pod 'AnyThinkMentaCustomAdapter', :path => '../AnyThinkMentaCustomAdapter.podspec'
  pod 'AnyThinkMentaCustomAdapterInland', :path => '../AnyThinkMentaCustomAdapterInland.podspec'
  pod 'AnyThinkKuaiShouSDKAdapter','6.4.55'
#  pod 'TPNMentaCustomAdapterInland', :path => '../TPNMentaCustomAdapterInland.podspec'
  
  #  pod 'MentaVlionBaseSDK', '6.00.30'
  #  pod 'MentaUnifiedSDK',   '6.00.30'
  #  pod 'MentaVlionSDK',     '6.00.30'
  #  pod 'MentaVlionAdapter', '6.00.30'
  #  pod 'MentaKSAdapter',    '6.00.30.1'
   
  
 pod 'MentaUnifiedSDK',    :path => '/Users/jdy/Desktop/Menta-iOS/MentaUnifiedSDK.podspec'
 pod 'MentaVlionBaseSDK',  :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionBaseSDK.podspec'
 pod 'MentaVlionSDK',      :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionSDK.podspec'
 pod 'MentaVlionAdapter',  :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionAdapter.podspec'
 pod 'MentaKSAdapter',     :path => '/Users/jdy/Desktop/Menta-iOS/MentaKSAdapter.podspec'

# pod 'MentaJDYunAdapter',  :path => '/Users/jdy/Desktop/Menta-iOS/MentaJDYunAdapter.podspec'
# pod 'MentaBaiduAdapter',  :path => '/Users/jdy/Desktop/Menta-iOS/MentaBaiduAdapter.podspec'
# pod 'MentaGDTAdapter',    :path => '/Users/jdy/Desktop/Menta-iOS/MentaGDTAdapter.podspec'
# pod 'MentaTanxAdapter',   :path => '/Users/jdy/Desktop/Menta-iOS/MentaTanxAdapter.podspec'
# pod 'MentaCSJAdapter',    :path => '/Users/jdy/Desktop/Menta-iOS/MentaCSJAdapter.podspec'
# pod 'MentaSigmobAdapter', :path => '/Users/jdy/Desktop/Menta-iOS/MentaSigmobAdapter.podspec'
# pod 'MentaIFLYAdapter',   :path => '/Users/jdy/Desktop/Menta-iOS/MentaIFLYAdapter.podspec'
# pod 'MentaWXminiAdapter', :path => '/Users/jdy/Desktop/Menta-iOS/MentaWXminiAdapter.podspec'
# pod 'MentaMeishuAdapter', :path => '/Users/jdy/Desktop/Menta-iOS/MentaMeishuAdapter.podspec'
# pod 'MentaJumoAdapter',   :path => '/Users/jdy/Desktop/Menta-iOS/MentaJumoAdapter.podspec'
  
  #海外

    # pod 'TPNiOS', '6.3.54'
    # pod 'TPNMentaCustomAdapter', :path => '../TPNMentaCustomAdapter.podspec'
    # pod 'TPNMentaCustomAdapterNew', :path => '../TPNMentaCustomAdapterNew.podspec'
    
    # pod 'MentaBaseGlobal',         '1.0.14'
    # pod 'MentaVlionGlobal',        '1.0.14'
    # pod 'MentaMediationGlobal',    '1.0.14'
    # pod 'MentaVlionGlobalAdapter', '1.0.14'

    # pod 'MentaVlionGlobal', :path => '/Users/jdy/Desktop/Menta-Global/MentaVlionGlobal.podspec'
    # pod 'MentaVlionGlobalAdapter', :path => '/Users/jdy/Desktop/Menta-Global/MentaVlionGlobalAdapter.podspec'
    # pod 'MentaMediationGlobal', :path => '/Users/jdy/Desktop/Menta-Global/MentaMediationGlobal.podspec'
    # pod 'MentaBaseGlobal', :path => '/Users/jdy/Desktop/Menta-Global/MentaBaseGlobal.podspec'
  
    pod 'TianmuSDK'

end 
