# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.0'
project 'AnyThinkSDKDemo.xcodeproj'

def share_pods
  
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MJRefresh'


end

target 'AnyThinkSDKDemo' do
  
  post_install do |installer|
        installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
        end
      end
  
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
  share_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'AnyThinkMentaCustomAdapter', :path => '../AnyThinkMentaCustomAdapter.podspec'
  
  # pod 'MentaUnifiedSDK',   :path => '/Users/jdy/Desktop/Menta-iOS/MentaUnifiedSDK.podspec'
  # pod 'MentaVlionBaseSDK', :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionBaseSDK.podspec'
  # pod 'MentaVlionSDK',     :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionSDK.podspec'
  # pod 'MentaVlionAdapter', :path => '/Users/jdy/Desktop/Menta-iOS/MentaVlionAdapter.podspec'
  
#  pod 'AnyThinkiOS','6.3.54'
  pod 'TianmuSDK'

end 
