default_platform(:ios)

platform :ios do
  desc "Build and sign the IPA"
  lane :build do
    gym(
      workspace: "AnyThinkSDKDemo/AnyThinkSDKDemo.xcworkspace", 
      scheme: "AnyThinkSDKDemo",
      clean: true,
      output_directory: "./Build",
      export_options: {
        method: "development",
      }
    )
    sh "chmod +x ./pgyer_upload.sh"
    sh "./pgyer_upload.sh -k 9a57e69885455c0dd7c80c02f6d438a5 ../Build/AnyThinkSDKDemo.ipa"
  end
end
